#!/usr/bin/env bash
# Bash script that displays : The content of the current directory. In a list and only the parts after the dash.
#!/usr/bin/env bash
for file in *; do
	#skip hidden files and directories
	[[ "$file" == .* || -d "$file" ]] && continue

	# If the filename contains a dash, extract and display the part after the first dash
	if [[ "$file" == *-* ]]; then
		echo "${file#*-}"
	fi
done

