#!/bin/bash
count=1
while [ $count -le 20 ]; do
  echo -n "$count"
  case $count in
      4)
        echo " and then bad luck from China"
        ;;
      9)
        echo " and then bad luck from Japan"
        ;;
      17)
        echo " and then bad luck from Italy"
        ;;
      *)
        echo ""
        ;;
    esac
    count=$((count + 1))
done
