#!/usr/bin/env bash
for file in *; do
    [ -d "$file" ] && continue
    [[ "$file" == .* ]] && continue
    if [[ "$file" == *-* ]]; then
        echo "- ${file#*-}"
    else
        echo "- $file"
    fi
done

