#!/usr/bin/env bash
#Script that uses SIGKILL to kill 7-highlander process
# shellcheck disable=SC2009

if pgrep -f "7-highlander" > /dev/null; then
	pkill -9 -f "7-highlander"
else
	echo "7-highlander process not found or not running."
fi
