#!/usr/bin/env bash
#Write a Bash script that displays : The content of the current directory in a list format, where only the part of the name after the first dash is displayed.
for file in *; do
    [ -d "$file" ] && continue
    [[ "$file" == .* ]] && continue
    if [[ "$file" == *-* ]]; then
        echo "- ${file#*-}"
    else
        echo "- $file"
    fi
done

