#!/usr/bin/env bash
# Bash script that checks if the file 'school' exists and displays status messages. Uses if and else statements only.
if [ -e "school" ]; then
    echo "school file exists"
    if [ -s "school" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "school" ]; then
        echo "school file is a regular"
    fi
else
    echo "school file does not exist"
fi

